# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Promote Branch

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  security-events: write
  id-token: write
  actions: read

jobs:
  presubmit:
    name: Presubmit
    uses: ./.github/workflows/presubmit.yaml
    permissions:
      contents: read
      id-token: write
      security-events: write
      actions: read
    secrets: inherit

  promote:
    needs: presubmit
    name: Promote to master
    runs-on: ubuntu-latest
    if: success()

    environment:
      name: master-branch
      url: ${{github.server_url}}/${{github.repository}}/tree/master

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          fetch-depth: 0

      - name: Push
        id: update-branch
        run: |
          echo "new_sha1=$(git rev-parse HEAD)" >> "${GITHUB_OUTPUT}"

          git fetch origin master
          git checkout master
          echo "old_sha1=$(git rev-parse HEAD)" >> "${GITHUB_OUTPUT}"

          git push origin ${{github.sha}}:master
